name: Tests

on: [push, pull_request]

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        moodle-branch: ['MOODLE_500_STABLE', 'main']
        php: ['8.3', '8.4']
        database: ['mariadb', 'pgsql']

    steps:
      - name: checkout plugin
        uses: actions/checkout@v4
        with:
          path: this-plugin
          ref: MOODLE_500_STABLE

      - name: setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: max_input_vars=5000
          tools: composer:v2.5
          coverage: pcov

      - name: setup pgsql
        if: ${{ matrix.database == 'pgsql' }}
        uses: m4nu56/postgresql-action@v1
        with:
          postgresql version: 15
          postgresql user: test
          postgresql password: test

      - name: setup mariadb
        if: ${{ matrix.database == 'mariadb' }}
        uses: getong/mariadb-action@v1.1
        with:
            mysql user: 'test'
            mysql password: 'test'

      - name: composer
        run: |
           composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci
           echo $(cd ci/bin; pwd) >> $GITHUB_PATH
           echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
           sudo locale-gen en_AU.UTF-8

      - name: install Moodle
        run: moodle-plugin-ci install --db-host=127.0.0.1 --db-user=test --db-pass=test --plugin this-plugin
        env:
          DB: ${{ matrix.database }}
          MOODLE_BRANCH: ${{ matrix.moodle-branch }}

      - name: phplint
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci --ansi phplint

      - name: phpmd
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci --ansi phpmd

      - name: phpdoc
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci --ansi phpdoc

      - name: codechecker
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci --ansi codechecker

      - name: validate
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci --ansi validate

      - name: savepoints
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci --ansi savepoints

      - name: grunt
        if: ${{ matrix.moodle-branch == 'main'}}
        run: moodle-plugin-ci --ansi grunt

      - name: mustache
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci --ansi mustache

      - name: phpunit
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci --ansi phpunit --testdox --coverage-text --coverage-clover

      - name: privacy
        if: ${{ matrix.moodle-branch == 'main'}}
        run: vendor/bin/phpunit --colors --no-coverage --testsuite tool_dataprivacy_testsuite,tool_policy_testsuite,core_privacy_testsuite
        working-directory: moodle

      - name: other
        if: ${{ matrix.moodle-branch == 'main'}}
        run: vendor/bin/phpunit --colors --no-coverage --testsuite core_availability_testsuite
        working-directory: moodle

      - name: coveralls
        if: ${{ matrix.moodle-branch == 'main'}}
        run: moodle-plugin-ci coveralls-upload || true
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: firefox
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci --ansi behat

      - name: faildump
        if: ${{ failure() && steps.behat.outcome == 'failure' }}
        uses: actions/upload-artifact@v4
        with:
          name: firefox faildump (${{ join(matrix.*, ', ') }})
          path: ${{ github.workspace }}/moodledata/behat_dump
          retention-days: 7
          if-no-files-found: ignore
 
      - name: chrome
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci --ansi behat --profile chrome

      - name: firefox classic
        id: behat
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci --ansi behat --suite="classic"
      
      - name: chrome classic
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci --ansi behat  --suite="classic" --profile chrome

      - name: admin bookmarks
        if: ${{ matrix.moodle-branch == 'main'}}
        run: moodle-plugin-ci --ansi behat --auto-rerun=0 --profile chrome public/blocks/admin_bookmarks
        working-directory: moodle

      - name: admin xmldb
        if: ${{ matrix.moodle-branch == 'main'}}
        run: moodle-plugin-ci --ansi behat --auto-rerun=0 --profile chrome public/admin/tool/xmldb
        working-directory: moodle
