name: Tests

on: [push, pull_request]

jobs:
  ci:
    name: ci
    runs-on: ubuntu-18.04

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: 'postgres'
          POSTGRES_HOST_AUTH_METHOD: 'trust'
        options: --health-cmd="pg_isready" --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 5432:5432
      mariadb:
        image: mariadb
        env:
          MYSQL_USER: 'root'
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
        options: --health-cmd="mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 3
        ports:
          - 3306:3306

    strategy:
      fail-fast: false
      matrix:
        moodle-branch: ['master', 'MOODLE_311_STABLE', 'MOODLE_310_STABLE', 'MOODLE_39_STABLE']
        php: ['7.4', '7.3']
        database: ['mariadb', 'pgsql']

    steps:
      - name: checkout plugin
        uses: actions/checkout@v2
        with:
          path: this-plugin

      - name: setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, pgsql, mysqli
          tools: composer, behat, phpunit, phpmd, phpcbf, phpcpd, psalm, phpcs
          coverage: xdebug

      - name: checkout moodle-plugin-ci
        uses: actions/checkout@v2
        with:
          repository: moodlehq/moodle-plugin-ci
          path: ci

      - name: other
        run: |
           cd ci
           composer install
           echo "$(cd bin; pwd)" >> $GITHUB_PATH
           echo "$(cd vendor/bin; pwd)" >> $GITHUB_PATH
           sudo locale-gen en_AU.UTF-8

      - name: install Moodle
        run: moodle-plugin-ci install --db-host=127.0.0.1 --plugin this-plugin
        env:
          DB: ${{ matrix.database }}
          MOODLE_BRANCH: ${{ matrix.moodle-branch }}
      
      - name: phplint
        run: moodle-plugin-ci phplint --ansi

      - name: phpcpd
        run: moodle-plugin-ci phpcpd --ansi

      - name: phpmd
        run: moodle-plugin-ci phpmd --ansi

      - name: phpdoc
        run: moodle-plugin-ci --ansi phpdoc

      - name: codechecker
        run: moodle-plugin-ci codechecker --ansi

      - name: validate
        run: moodle-plugin-ci validate --ansi

      - name: savepoints
        run: moodle-plugin-ci savepoints --ansi

      - name: mustache
        run: moodle-plugin-ci mustache --ansi

      - name: grunt
        run: moodle-plugin-ci grunt --ansi

      - name: phpunit 
        run: moodle-plugin-ci phpunit --ansi --coverage-text --coverage-clover

      - name: firefox
        run: moodle-plugin-ci behat --ansi
      
      - name: chrome
        run: moodle-plugin-ci behat --ansi --profile chrome

      - name: firefox classic
        run: moodle-plugin-ci behat --ansi --suite="classic"
      
      - name: chrome classic
        run: moodle-plugin-ci behat --ansi --suite="classic" --profile chrome

      - name: admin bookmarks
        run: php admin/tool/behat/cli/run.php --profile=chrome --tags=@block_admin_bookmarks
        working-directory: moodle

      - name: privacy
        run: vendor/bin/phpunit --colors --no-coverage --testsuite tool_dataprivacy_testsuite,tool_policy_testsuite,core_privacy_testsuite
        working-directory: moodle

      - name: coveralls
        env:
          COVERALLS_RUN_LOCALLY: true
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: moodle-plugin-ci coveralls-upload
        if: matrix.moodle-branch == 'master'
